WORKING_DIR = "."

DRIVER_FILE_NAME = "driver_data.csv"
ORDER_FILE_NAME = "order_data.csv"

BIKE = 'BIKE'
CAR = 'CAR'

VEHICLE_TYPE_2_DRIVER_CAPACITY = {BIKE: 10, CAR: 30}
VEHICLE_TYPE_2_DRIVER_SPEED = {BIKE: 15, CAR: 30}

MAX_PICKUP_DISTANCE_IN_METERS = 7_500
SOFT_MAX_DISTANCE_IN_METERS = 4_000

LATE_DELIVERY_PER_SEC_PENALTY = 1_000_000
ABOVE_MAX_DISTANCE_PER_METER_PENALTY = 1_000
