WORKING_DIR = "."

DRIVER_FILE_NAME = "driver_data.csv"
ORDER_FILE_NAME = "order_data.csv"

DRIVER_CAPACITY = 20
DRIVER_SPEED = 15
MAX_PICKUP_DISTANCE_IN_METERS = 7_500
SOFT_MAX_DISTANCE_IN_METERS = 4_000

LATE_DELIVERY_PER_SEC_PENALTY = 1_000_000
ABOVE_MAX_DISTANCE_PER_METER_PENALTY = 1_000
